name: soulib

app: dockerfile

options:
  ports: 5000
  dockerfile: Dockerfile
  env:
    - name: GITHUB_ISSUE_TOKEN
      secret: soulib-report-issues
    - name: GITHUB_ISSUE_REPO
      value: pkkong/library_crawler
    - name: PUBLIC_BASE_URL
      value: https://www.soulib.kr
    - name: SHARED_SHELVES_STORAGE
      value: postgres

context:
  git:
    url: https://github.com/pkkong/library_crawler.git
    branch: main
  preset: dockerfile
