import os

# Platform display labels (used for grouping in search results)
PLATFORM_LABELS = {
    "Kyobo_New": "교보(신버전)",
    "Kyobo": "교보",
    "YES24": "YES24",
    "FxLibrary": "기타",
    "Bookcube": "북큐브",
    "Mixed": "기타",
    "Aladin": "기타",
    "Unknown": "기타",
}

# Short nicknames for compact library display
LIBRARY_SHORT = {
    "yongsan": "용산",
    "mapo": "마포",
    "gangbuk": "강북",
    "gwangjin": "광진(소장)",
    "gwangjin_subs": "광진(구독)",
    "seongdong": "성동",
    "gangdong_owned": "강동(소장)",
    "gangdong_subs": "강동(구독)",
    "dobong": "도봉",
    "seodaemun_subs": "서대문(구독)",
    "seodaemun_owned": "서대문(소장)",
    "junggu": "중구",
    "jungnang": "중랑",
    "gwanak": "관악",
    "nowon": "노원",
    "guro": "구로",
    "seoul": "서울시",
    "sen_owned": "서울교육청(소장)",
    "sen_subs": "서울교육청(구독)",
    "seongbuk": "성북",
    "gangnam": "강남",
    "yeongdeungpo": "영등포",
    "dongdaemun": "동대문",
    "dongjak": "동작",
    "gangseo": "강서",
    "seocho": "서초",
    "eunpyeong": "은평",
    "jongno": "종로",
    "songpa_subs": "송파",
    "songpa_owned": "송파",
    "geumcheon": "금천",
    "yangcheon_subs": "양천",
    "yangcheon_owned": "양천",
}

# Override short names without subscription/owned qualifiers
LIBRARY_SHORT = {
    "yongsan": "용산",
    "mapo": "마포",
    "gangbuk": "강북",
    "gwangjin": "광진",
    "gwangjin_subs": "광진",
    "seongdong": "성동",
    "gangdong_owned": "강동",
    "gangdong_subs": "강동",
    "dobong": "도봉",
    "seodaemun_subs": "서대문",
    "seodaemun_owned": "서대문",
    "junggu": "중구",
    "jungnang": "중랑",
    "gwanak": "관악",
    "nowon": "노원",
    "guro": "구로",
    "seoul": "서울도서관",
    "sen_owned": "서울교육청",
    "sen_subs": "서울교육청",
    "seongbuk": "성북",
    "gangnam": "강남",
    "yeongdeungpo": "영등포",
    "dongdaemun": "동대문",
    "dongjak": "동작",
    "gangseo": "강서",
    "seocho": "서초",
    "eunpyeong": "은평",
    "jongno": "종로",
    "songpa_subs": "송파",
    "songpa_owned": "송파",
    "geumcheon": "금천",
    "yangcheon_subs": "양천",
    "yangcheon_owned": "양천",
}

# Base paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(BASE_DIR)
DATA_DIR = os.path.join(ROOT_DIR, "data")
CRAWLER_DIR = os.path.join(ROOT_DIR, "crawler")
STATUS_FILE = os.path.join(DATA_DIR, "crawler_status.json")

# API keys
ODCLOUD_API_KEY = os.environ.get(
    "ODCLOUD_API_KEY",
    "0R7RBsF2YmoEs3gIwDmbZyv/SYGXCeJwZWyhhlsvX3qcSuGu89uzFL9/sODpXk3tmHa2nt7DP7yZJ/4RJ14FEA==",
).strip()
SEOUL_API_KEY = os.environ.get("SEOUL_API_KEY", "745942496d6b6f6e383774624c4c56").strip()

# Library definitions
LIBRARIES = {
    # Scrapy (Kyobo 신버전)
    "yongsan": {
        "name": "용산구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "yongsan_db.csv"),
        "cmd": ["scrapy", "crawl", "yongsan_kyobo", "-O", "../data/yongsan_db.csv"],
        "total_count_url": "https://ebook.yslibrary.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": "https://ebook.yslibrary.or.kr",
        "library_name": "용산구 전자도서관",
        "homepage_url": "https://ebook.yslibrary.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "mapo": {
        "name": "마포구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "mapo_db.csv"),
        "cmd": ["scrapy", "crawl", "mapo_kyobo", "-O", "../data/mapo_db.csv"],
        "total_count_url": "https://ebook.mapo.go.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "마포구 전자도서관",
        "homepage_url": "https://ebook.mapo.go.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "gangbuk": {
        "name": "강북구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gangbuk_db.csv"),
        "cmd": ["scrapy", "crawl", "gangbuk_kyobo", "-O", "../data/gangbuk_db.csv"],
        "total_count_url": "https://ebook.gblib.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "강북문화정보도서관",
        "homepage_url": "https://ebook.gblib.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "gwangjin": {
        "name": "광진구 (소장)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gwangjin_db.csv"),
        "cmd": ["scrapy", "crawl", "gwangjin_kyobo", "-O", "../data/gwangjin_db.csv"],
        "total_count_url": "https://ebook.gwangjinlib.seoul.kr:446/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "광진구립도서관 (소장)",
        "homepage_url": "https://ebook.gwangjinlib.seoul.kr:446/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "gwangjin_subs": {
        "name": "광진구 (구독)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gwangjin_subs_db.csv"),
        "cmd": ["scrapy", "crawl", "gwangjin_subscription", "-O", "../data/gwangjin_subs_db.csv"],
        "total_count_url": "https://gwangjin.dkyobobook.co.kr/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "광진구립도서관 (구독)",
        "homepage_url": "https://gwangjin.dkyobobook.co.kr/",
        "content_path": "/content/contentView.ink",
        "platform": "Kyobo_New",
        "service_type": "Subscription",
    },
    "seongdong": {
        "name": "성동구 (북큐브)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "seongdong_db.csv"),
        "cmd": ["scrapy", "crawl", "seongdong_bookcube", "-O", "../data/seongdong_db.csv"],
        "total_count_url": "https://ebook.sdlib.or.kr/FxLibrary/product/list/?itemdv=1&sort=3&page=1&itemCount=20&pageCount=10&category=&middlecategory=&cateopt=total&group_num=recommand&catenavi=main&category_type=book&searchoption=&keyoption=&keyoption2=&keyword=&listfilter=all_list&selectview=list_on&searchType=&name=&publisher=&author=&terminal=",
        "url_prefix": None,
        "library_name": "성동구립도서관",
        "homepage_url": "https://ebook.sdlib.or.kr/",
        "platform": "Bookcube",
        "service_type": "Owned",
    },
    "gangdong_owned": {
        "name": "강동구 (YES24)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gangdong_owned_db.csv"),
        "cmd": ["scrapy", "crawl", "gangdong_yes24", "-O", "../data/gangdong_owned_db.csv"],
        "total_count_url": "https://ebook.gdlibrary.or.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": None,
        "library_name": "강동구립도서관",
        "homepage_url": "https://ebook.gdlibrary.or.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "gangdong_subs": {
        "name": "강동구 (구독)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gangdong_subs_db.csv"),
        "cmd": ["scrapy", "crawl", "gangdong_kyobo", "-O", "../data/gangdong_subs_db.csv"],
        "total_count_url": "https://gdlib.dkyobobook.co.kr/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "강동구립도서관 (구독)",
        "homepage_url": "https://gdlib.dkyobobook.co.kr/",
        "content_path": "/content/contentView.ink",
        "platform": "Kyobo_New",
        "service_type": "Subscription",
    },
    "dobong": {
        "name": "도봉구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "dobong_db.csv"),
        "cmd": ["scrapy", "crawl", "dobong_kyobo", "-O", "../data/dobong_db.csv"],
        "total_count_url": "https://elib.dobong.kr/Kyobo_T3/Content/ebook/ebook_Main.asp?product_cd=001&content_all=Y&listnum=80",
        "url_prefix": None,
        "library_name": "도봉구립도서관",
        "homepage_url": "https://elib.dobong.kr/",
        "platform": "Kyobo",
        "service_type": "Owned",
    },
    "seodaemun_subs": {
        "name": "서대문구 (구독)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "seodaemun_subs_db.csv"),
        "cmd": ["scrapy", "crawl", "seodaemun_subscription", "-O", "../data/seodaemun_subs_db.csv"],
        "total_count_url": "https://sdmlib.dkyobobook.co.kr/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&pageIndex=1",
        "url_prefix": None,
        "library_name": "서대문구립도서관 (구독)",
        "homepage_url": "https://sdmlib.dkyobobook.co.kr/",
        "content_path": "/content/contentView.ink",
        "platform": "Kyobo_New",
        "service_type": "Subscription",
    },
    "seodaemun_owned": {
        "name": "서대문구 (소장)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "seodaemun_owned_db.csv"),
        "cmd": ["scrapy", "crawl", "seodaemun_owned", "-O", "../data/seodaemun_owned_db.csv"],
        "total_count_url": "https://ebook.sdm.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&pageIndex=1",
        "url_prefix": None,
        "library_name": "서대문구립도서관 (소장)",
        "homepage_url": "https://ebook.sdm.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "junggu": {
        "name": "중구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "junggu_db.csv"),
        "cmd": ["scrapy", "crawl", "junggu_kyobo", "-O", "../data/junggu_db.csv"],
        "total_count_url": "https://ebook.junggulib.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "중구통합전자도서관",
        "homepage_url": "https://ebook.junggulib.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "jungnang": {
        "name": "중랑구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "jungnang_db.csv"),
        "cmd": ["scrapy", "crawl", "jungnang_kyobo", "-O", "../data/jungnang_db.csv"],
        "total_count_url": "https://ebook.jungnanglib.seoul.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "중랑구립정보도서관",
        "homepage_url": "https://ebook.jungnanglib.seoul.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "gwanak": {
        "name": "관악구 (YES24)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gwanak_db.csv"),
        "cmd": ["scrapy", "crawl", "gwanak_yes24", "-O", "../data/gwanak_db.csv"],
        "total_count_url": "https://e-lib.gwanak.go.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": None,
        "library_name": "관악구통합도서관",
        "homepage_url": "https://e-lib.gwanak.go.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "nowon": {
        "name": "노원구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "nowon_db.csv"),
        "cmd": ["scrapy", "crawl", "nowon_kyobo", "-O", "../data/nowon_db.csv"],
        "total_count_url": "https://eb.nowonlib.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "노원구립도서관",
        "homepage_url": "https://eb.nowonlib.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "guro": {
        "name": "구로구 (교보)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "guro_db.csv"),
        "cmd": ["scrapy", "crawl", "guro_kyobo", "-O", "../data/guro_db.csv"],
        "total_count_url": "https://ebook.guro.go.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "구로구립도서관",
        "homepage_url": "https://ebook.guro.go.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "dongdaemun": {
        "name": "동대문구 (교보 신버전)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "dongdaemun_db.csv"),
        "cmd": ["scrapy", "crawl", "dongdaemun_kyobo", "-O", "../data/dongdaemun_db.csv"],
        "total_count_url": "https://e-book.l4d.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "동대문구 도서관",
        "homepage_url": "https://e-book.l4d.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "dongjak": {
        "name": "동작구 (교보 신버전)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "dongjak_db.csv"),
        "cmd": ["scrapy", "crawl", "dongjak_kyobo", "-O", "../data/dongjak_db.csv"],
        "total_count_url": "https://ebook.dongjak.go.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "동작구 구립도서관",
        "homepage_url": "https://ebook.dongjak.go.kr/elibrary-front/main.ink",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "seocho": {
        "name": "서초구 (교보 신버전)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "seocho_db.csv"),
        "cmd": ["scrapy", "crawl", "seocho_kyobo", "-O", "../data/seocho_db.csv"],
        "total_count_url": "https://ebook.seocholib.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "서초구 전자도서관",
        "homepage_url": "https://ebook.seocholib.or.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "seongbuk": {
        "name": "성북구 (교보 신버전)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "seongbuk_db.csv"),
        "cmd": ["scrapy", "crawl", "seongbuk_kyobo", "-O", "../data/seongbuk_db.csv"],
        "total_count_url": "https://elibrary.sblib.seoul.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "성북구 도서관",
        "homepage_url": "https://elibrary.sblib.seoul.kr/",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "songpa_subs": {
        "name": "송파구 (구독)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "songpa_subs_db.csv"),
        "cmd": ["scrapy", "crawl", "songpa_subscription", "-O", "../data/songpa_subs_db.csv"],
        "total_count_url": "https://splib.dkyobobook.co.kr/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=80&pageIndex=1&recordCount=20",
        "url_prefix": None,
        "library_name": "송파구립도서관 (구독)",
        "homepage_url": "https://splib.dkyobobook.co.kr/main.ink",
        "content_path": "/content/contentView.ink",
        "platform": "Kyobo_New",
        "service_type": "Subscription",
    },
    "songpa_owned": {
        "name": "송파구 (소장)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "songpa_owned_db.csv"),
        "cmd": ["scrapy", "crawl", "songpa_yes24", "-O", "../data/songpa_owned_db.csv"],
        "total_count_url": "https://ebook.splib.or.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": None,
        "library_name": "송파구 도서관 (소장)",
        "homepage_url": "https://ebook.splib.or.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "yeongdeungpo": {
        "name": "영등포구 (YES24)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "yeongdeungpo_db.csv"),
        "cmd": ["scrapy", "crawl", "yeongdeungpo_yes24", "-O", "../data/yeongdeungpo_db.csv"],
        "total_count_url": "https://ebook.ydplib.or.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": "https://ebook.ydplib.or.kr",
        "library_name": "영등포구 도서관",
        "homepage_url": "https://ebook.ydplib.or.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "gangseo": {
        "name": "강서구 (YES24)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gangseo_db.csv"),
        "cmd": ["scrapy", "crawl", "gangseo_yes24", "-O", "../data/gangseo_db.csv"],
        "total_count_url": "https://ebook.gangseo.seoul.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": None,
        "library_name": "강서구 전자도서관",
        "homepage_url": "https://ebook.gangseo.seoul.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "eunpyeong": {
        "name": "은평구 (기타)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "eunpyeong_db.csv"),
        "cmd": ["scrapy", "crawl", "eunpyeong_native", "-O", "../data/eunpyeong_db.csv"],
        "total_count_url": "https://epbook.eplib.or.kr/ebookPlatform/Homepage/TotalEbook.do?libCode=111042&userId=null&majorCategory=000&subCategory=&collection=1&orderOption=1&currentCount=1&pageCount=20",
        "url_prefix": None,
        "library_name": "은평구립도서관",
        "homepage_url": "https://epbook.eplib.or.kr/ebookPlatform/home/main.do",
        "platform": "Unknown",
        "service_type": "Owned",
    },
    "jongno": {
        "name": "종로구 (YES24)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "jongno_db.csv"),
        "cmd": ["scrapy", "crawl", "jongno_yes24", "-O", "../data/jongno_db.csv"],
        "total_count_url": "https://elib.jongno.go.kr/ebook/?mode=total&sort=pubdt&cate_id=&page_num=1",
        "url_prefix": None,
        "library_name": "종로구 전자도서관",
        "homepage_url": "https://elib.jongno.go.kr/",
        "platform": "YES24",
        "service_type": "Owned",
    },
    "geumcheon": {
        "name": "금천구(북큐브)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "geumcheon_db.csv"),
        "cmd": ["scrapy", "crawl", "geumcheon_bookcube", "-O", "../data/geumcheon_db.csv"],
        "total_count_url": "https://elib.geumcheonlib.seoul.kr/FxLibrary/product/list/?itemdv=1&sort=3&page=1&itemCount=20&pageCount=10&category=&middlecategory=&cateopt=total&group_num=recommand&catenavi=main&category_type=book&searchoption=&keyoption=&keyoption2=&keyword=&listfilter=all_list&selectview=list_on&searchType=&name=&publisher=&author=&terminal=",
        "url_prefix": None,
        "library_name": "금천구립도서관",
        "homepage_url": "https://elib.geumcheonlib.seoul.kr/FxLibrary/index/",
        "platform": "Bookcube",
        "service_type": "Owned",
    },
    "yangcheon_subs": {
        "name": "양천구 (구독)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "yangcheon_subs_db.csv"),
        "cmd": ["scrapy", "crawl", "yangcheon_subscription", "-O", "../data/yangcheon_subs_db.csv"],
        "total_count_url": "https://yclib.dkyobobook.co.kr/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "양천구립도서관 (구독)",
        "homepage_url": "https://yclib.dkyobobook.co.kr/main.ink",
        "content_path": "/content/contentView.ink",
        "platform": "Kyobo_New",
        "service_type": "Subscription",
    },
    "yangcheon_owned": {
        "name": "양천구 (소장)",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "yangcheon_owned_db.csv"),
        "cmd": ["scrapy", "crawl", "yangcheon_owned", "-O", "../data/yangcheon_owned_db.csv"],
        "total_count_url": "https://ebook.yangcheon.or.kr/elibrary-front/content/contentList.ink?cttsDvsnCode=001&contentAll=Y&selViewCnt=20&recordCount=20&pageIndex=1",
        "url_prefix": None,
        "library_name": "양천구립도서관 (소장)",
        "homepage_url": "https://ebook.yangcheon.or.kr/elibrary-front/main.ink",
        "platform": "Kyobo_New",
        "service_type": "Owned",
    },
    "gangnam": {
        "name": "강남구 전자도서관",
        "type": "scrapy",
        "db_file": os.path.join(DATA_DIR, "gangnam_db.csv"),
        "cmd": ["scrapy", "crawl", "gangnam_native", "-O", "../data/gangnam_db.csv"],
        "total_count_url": "https://ebook.gangnam.go.kr/elibbook/book_category.asp?mode=&page_num=1&branch=99&supply_code=&strSort=p&ldav=",
        "url_prefix": None,
        "library_name": "강남구 전자도서관",
        "homepage_url": "https://ebook.gangnam.go.kr/",
        "platform": "Unknown",
        "service_type": "Owned",
    },

    # Custom scripts
    "seoul": {
        "name": "서울도서관",
        "type": "custom",
        "db_file": os.path.join(DATA_DIR, "seoul_db.csv"),
        "cmd": ["python", "collect_seoul.py"],
        "url_prefix": None,
        "library_name": "서울도서관 (복합)",
        "homepage_url": "https://elib.seoul.go.kr/",
        "platform": "Mixed",
        "service_type": "Owned",
    },
    "sen_owned": {
        "name": "서울교육청 (소장)",
        "type": "custom",
        "db_file": os.path.join(DATA_DIR, "sen_owned_db.csv"),
        "cmd": ["python", "download_sen_owned_db.py"],
        "url_prefix": None,
        "library_name": "서울시교육청 (소장)",
        "homepage_url": "https://e-lib.sen.go.kr/",
        "platform": "Mixed",
        "service_type": "Owned",
    },
    "sen_subs": {
        "name": "서울교육청 (구독)",
        "type": "custom",
        "db_file": os.path.join(DATA_DIR, "sen_subs_db.csv"),
        "cmd": ["python", "download_sen_subs_db.py"],
        "url_prefix": None,
        "library_name": "서울시교육청 (구독)",
        "homepage_url": "https://e-lib.sen.go.kr/",
        "platform": "Mixed",
        "service_type": "Subscription",
    },
}
