def _book(slug, title, author="", publisher=""):
    return {
        "slug": slug,
        "title": title,
        "author": author,
        "publisher": publisher,
        "summary": f"{title} 전자책을 서울 전자도서관에서 검색하고, 보유 도서관과 대출 가능 여부를 실시간으로 확인하세요.",
        "keywords": [f"{title} 전자도서관", f"{title} 전자책", f"{title} 대출"],
    }


_SEO_BOOK_ROWS = [
    ("project-hail-mary", "프로젝트 헤일메리", "앤디 위어", "알에이치코리아"),
    ("bulpyeonhan-pyeonuijeom", "불편한 편의점", "김호연", "나무옆의자"),
    ("welcome-to-the-hyunam-dong-bookshop", "어서 오세요, 휴남동 서점입니다", "황보름", "클레이하우스"),
    ("saynos-teaching", "세이노의 가르침", "세이노", "데이원"),
    ("the-reverse", "역행자", "자청", "웅진지식하우스"),
    ("trend-korea-2026", "트렌드 코리아 2026", "김난도 외", "미래의창"),
    ("human-acts", "소년이 온다", "한강", "창비"),
    ("the-vegetarian", "채식주의자", "한강", "창비"),
    ("we-do-not-part", "작별하지 않는다", "한강", "문학동네"),
    ("the-white-book", "흰", "한강", "문학동네"),
    ("small-things-like-these", "이처럼 사소한 것들", "클레어 키건", "다산책방"),
    ("contradiction", "모순", "양귀자", "쓰다"),
    ("almond", "아몬드", "손원평", "창비"),
    ("dallergut-dream-department-store", "달러구트 꿈 백화점", "이미예", "팩토리나인"),
    ("dallergut-dream-department-store-2", "달러구트 꿈 백화점 2", "이미예", "팩토리나인"),
    ("marigold-mind-laundry", "메리골드 마음 세탁소", "윤정은", "북로망스"),
    ("proof-of-the-sphere", "구의 증명", "최진영", "은행나무"),
    ("pachinko-1", "파친코 1", "이민진", "인플루엔셜"),
    ("pachinko-2", "파친코 2", "이민진", "인플루엔셜"),
    ("greenhouse-at-the-end-of-the-earth", "지구 끝의 온실", "김초엽", "자이언트북스"),
    ("if-we-cannot-move-at-the-speed-of-light", "우리가 빛의 속도로 갈 수 없다면", "김초엽", "허블"),
    ("thousand-blues", "천 개의 파랑", "천선란", "허블"),
    ("harry-potter-sorcerers-stone", "해리 포터와 마법사의 돌", "J.K. 롤링", "문학수첩"),
    ("demian", "데미안", "헤르만 헤세", "민음사"),
    ("the-stranger", "이방인", "알베르 카뮈", "민음사"),
    ("the-old-man-and-the-sea", "노인과 바다", "어니스트 헤밍웨이", "민음사"),
    ("animal-farm", "동물농장", "조지 오웰", "민음사"),
    ("nineteen-eighty-four", "1984", "조지 오웰", "민음사"),
    ("brave-new-world", "멋진 신세계", "올더스 헉슬리", "소담출판사"),
    ("the-little-prince", "어린 왕자", "앙투안 드 생텍쥐페리", "열린책들"),
    ("where-the-crawdads-sing", "가재가 노래하는 곳", "델리아 오언스", "살림"),
    ("midnight-library", "미드나잇 라이브러리", "매트 헤이그", "인플루엔셜"),
    ("even-if-this-love-disappears-tonight", "오늘 밤, 세계에서 이 사랑이 사라진다 해도", "이치조 미사키", "모모"),
    ("last-train-station", "세상의 마지막 기차역", "무라세 다케시", "모모"),
    ("miracles-of-the-namiya-general-store", "나미야 잡화점의 기적", "히가시노 게이고", "현대문학"),
    ("devotion-of-suspect-x", "용의자 X의 헌신", "히가시노 게이고", "재인"),
    ("swan-and-bat", "백조와 박쥐", "히가시노 게이고", "현대문학"),
    ("sapiens", "사피엔스", "유발 하라리", "김영사"),
    ("guns-germs-and-steel", "총, 균, 쇠", "재레드 다이아몬드", "문학사상"),
    ("factfulness", "팩트풀니스", "한스 로슬링", "김영사"),
    ("psychology-of-money", "돈의 심리학", "모건 하우절", "인플루엔셜"),
    ("rich-dad-poor-dad", "부자 아빠 가난한 아빠", "로버트 기요사키", "민음인"),
    ("the-one-thing", "원씽", "게리 켈러", "비즈니스북스"),
    ("atomic-habits", "아주 작은 습관의 힘", "제임스 클리어", "비즈니스북스"),
    ("historys-usefulness", "역사의 쓸모", "최태성", "다산초당"),
    ("wide-and-shallow-knowledge", "지적 대화를 위한 넓고 얕은 지식", "채사장", "웨일북"),
    ("wide-and-shallow-knowledge-zero", "지적 대화를 위한 넓고 얕은 지식 0", "채사장", "웨일북"),
    ("cosmos", "코스모스", "칼 세이건", "사이언스북스"),
    ("why-fish-dont-exist", "물고기는 존재하지 않는다", "룰루 밀러", "곰출판"),
    ("kluge", "클루지", "개리 마커스", "갤리온"),
    ("thinking-fast-and-slow", "생각에 관한 생각", "대니얼 카너먼", "김영사"),
    ("justice", "정의란 무엇인가", "마이클 샌델", "와이즈베리"),
    ("tyranny-of-merit", "공정하다는 착각", "마이클 샌델", "와이즈베리"),
    ("mans-search-for-meaning", "죽음의 수용소에서", "빅터 프랭클", "청아출판사"),
    ("courage-to-be-disliked", "미움받을 용기", "기시미 이치로", "인플루엔셜"),
    ("dont-let-mood-become-attitude", "기분이 태도가 되지 않게", "레몬심리", "갤리온"),
    ("dignity-of-words", "말의 품격", "이기주", "황소북스"),
    ("temperature-of-language", "언어의 온도", "이기주", "말글터"),
    ("i-decided-to-live-as-me", "나는 나로 살기로 했다", "김수현", "마음의숲"),
    ("school-nurse-ahn-eunyoung", "보건교사 안은영", "정세랑", "민음사"),
    ("from-siseon", "시선으로부터", "정세랑", "문학동네"),
    ("fifty-people", "피프티 피플", "정세랑", "창비"),
    ("bright-night", "밝은 밤", "최은영", "문학동네"),
    ("shokos-smile", "쇼코의 미소", "최은영", "문학동네"),
    ("very-faint-light", "아주 희미한 빛으로도", "최은영", "문학동네"),
    ("pagwa", "파과", "구병모", "위즈덤하우스"),
    ("wizard-bakery", "위저드 베이커리", "구병모", "창비"),
    ("place-of-flamingos", "홍학의 자리", "정해연", "엘릭시르"),
    ("perfect-happiness", "완전한 행복", "정유정", "은행나무"),
    ("seven-years-of-darkness", "7년의 밤", "정유정", "은행나무"),
    ("origin-of-species-novel", "종의 기원", "정유정", "은행나무"),
    ("my-brilliant-life", "두근두근 내 인생", "김애란", "창비"),
    ("outside-is-summer", "바깥은 여름", "김애란", "문학동네"),
    ("reasons-for-travel", "여행의 이유", "김영하", "문학동네"),
    ("murderers-memory-guide", "살인자의 기억법", "김영하", "복복서가"),
    ("only-two-people", "오직 두 사람", "김영하", "문학동네"),
    ("i-want-forbidden-things", "나는 소망한다 내게 금지된 것을", "양귀자", "쓰다"),
    ("wondo", "원도", "최진영", "한겨레출판"),
    ("alchemist", "연금술사", "파울로 코엘료", "문학동네"),
    ("grit", "그릿", "앤절라 더크워스", "비즈니스북스"),
    ("tools-of-titans", "타이탄의 도구들", "팀 페리스", "토네이도"),
    ("four-hour-workweek", "나는 4시간만 일한다", "팀 페리스", "다른상상"),
    ("leverage", "레버리지", "롭 무어", "다산북스"),
    ("millionaire-fastlane", "부의 추월차선", "엠제이 드마코", "토트"),
    ("wealth-bowl", "부자의 그릇", "이즈미 마사토", "다산북스"),
    ("wealthinking", "웰씽킹", "켈리 최", "다산북스"),
    ("wealth-scenario", "부의 시나리오", "오건영", "페이지2북스"),
    ("history-of-korean-money", "대한민국 돈의 역사", "홍춘욱", "상상스퀘어"),
    ("ebs-capitalism", "EBS 다큐프라임 자본주의", "EBS 자본주의 제작팀", "가나출판사"),
    ("surviving-inflation", "인플레이션에서 살아남기", "오건영", "페이지2북스"),
    ("most-important-thing", "투자에 대한 생각", "하워드 막스", "비즈니스맵"),
    ("common-sense-investing", "모든 주식을 소유하라", "존 보글", "비즈니스맵"),
    ("work-dignity", "일의 격", "신수정", "턴어라운드"),
    ("harvard-top-one-percent", "하버드 상위 1퍼센트의 비밀", "정주영", "한국경제신문"),
    ("how-do-you-live", "그대들, 어떻게 살 것인가", "요시노 겐자부로", "양철북"),
    ("stolen-focus", "도둑맞은 집중력", "요한 하리", "어크로스"),
    ("nudge", "넛지", "리처드 탈러", "리더스북"),
    ("pride-and-prejudice", "오만과 편견", "제인 오스틴", "민음사"),
    ("power-of-flexing", "유연함의 힘", "수잔 애쉬포드", "상상스퀘어"),
    ("selfish-gene", "이기적 유전자", "리처드 도킨스", "을유문화사"),
]


SEO_BOOKS = [_book(*row) for row in _SEO_BOOK_ROWS]
SEO_BOOK_BY_SLUG = {book["slug"]: book for book in SEO_BOOKS}
